# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopytka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesheet',
            name='minify',
            field=models.BooleanField(default=False),
        ),
    ]
